### ISSUE TITLE
V1.3.1 does not work in the notepad++ 8.3.3

### ISSUE THREAD

**Issue by jschuppe** [dail8859/ElasticTabstops#29] opened 2022-03-31 06:42 UTC
Since my update yesterdey to notepad++ V8.3.3 I can't see the ElasticsTabstop Plugin anymore

**Comment by dail8859** [comment] 2022-03-31 10:42
Duplicate of #28

**Comment by peterfnet** [comment] 2022-03-31 19:49
Ditto. Was unexpected. Not listed in plugin admin tool, file still exists in `C:\Program Files\Notepad++\plugins\ElasticTabstops\`, and it is not moved to the disabled plugin folder.

`"%APPDATA%\Notepad++\plugins\Config\ElasticTabstops.ini"` still exsists

**Comment by dail8859** [comment] 2022-03-31 20:09
> Was unexpected. Not listed in plugin admin tool, file still exists in C:\Program Files\Notepad++\plugins\ElasticTabstops\, and it is not moved to the disabled plugin folder.

Notepad++ did a horrible job about telling the user _why_ their plugin is no longer there and why it can't be installed.

**Closed as completed** 2022-04-06 21:58 UTC
